baseurl = "https://onegee.github.io/" # Controls base URL
languageCode = "en-US" # Controls site language
title = "ONEGEE" # Homepage title and page title suffix
paginate = 5 # Number of posts to show before paginating
theme = "after-dark" # Set default theme

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "UA-108362890-1" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments
SectionPagesMenu = "menu" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link


hasCJKLanguage = true
# summaryLength = 1

publishDir = "docs"

pygmentsUseClassic = true #使用pygment 确保安全好pygment并且有pygmentize命令
pygmentsCodefences = true #代码栅栏
pygmentsCodefencesGuessSyntax = true #自动判断语言
pygmentsUseClasses = true #使用css类
pygmentsStyle = "native"

pygmentsOptions = "linenos=inline" # nowrap=false,hl_lines=1,linenostart=1, http://pygments.org/docs/formatters/#HtmlFormatter
enableEmoji = true # enable Emoji use :emoji_name:


[params]
  description = "Hello, Here I am" # Suggested, controls default description meta
  author = "ONEGEE" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  show_menu = true # Optional, set true to enable section menu
  powered_by = true # Optional, set false to disable credits
  images = [""] # Suggested, controls default Open Graph images
  theme_variant = "" # Optional, for use to overriding default theme


[params.seo.webmaster_verifications]
  google = "" # Optional, Google verification code
  bing = "" # Optional, Bing verification code
  alexa = "" # Optional, Alexa verification code
  yandex = "" # Optional, Yandex verification code

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "post/about"

# keywords = [
#  "blog",
# ]
